name:               Pod-Simple-Wiki
abstract:           A class for creating Pod to Wiki filters.
version:            0.07
version_from:       lib/Pod/Simple/Wiki.pm
installdirs:        site
requires:
    Pod::Simple:                   0

distribution_type:  module
license:            perl
generated_by:       hand
