--- #YAML:1.0
name:               Pod-Simple-Wiki
version:            0.10
abstract:           A class for creating Pod to Wiki filters.
author:
    - John McNamara (jmcnamara@cpan.org)
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Pod::Simple:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
